In [8]:
import numpy as np

In [9]:
num = np.array((1,2,3,4))

In [10]:
print(num)

[1 2 3 4]


In [17]:
num2 = np.array(["a","b","c","d"])

In [18]:
print(num2)

['a' 'b' 'c' 'd']


In [24]:
num=np.array((1))
print(num)

1


In [25]:
print(num.ndim)

0


In [30]:
num3=np.array(((1,2,3),(6,7,8)))

In [32]:
print(num3)
print("dimention= ",num3.ndim)

[[1 2 3]
 [6 7 8]]
dimention=  2


In [ ]:
#to intailize numpuy array
# we have to use np.zeros() method 

In [33]:
intailize =np.zeros([2,3])
print(intailize)
print(type(intailize))
print('dimention= ',intailize.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
dimention=  2


In [1]:
import numpy as np
#to check its datatype of one array
n =np.array(["10","20","30"])
print(n.dtype)

<U2


In [2]:
#to convert to  another datatype
n2=n.astype("i")
print(n2)

[10 20 30]


In [9]:
num =np.array([19,40,56,12])
print(num[0])

19


In [10]:
print(num[-1])

12


In [11]:
print(num[2])

56


In [7]:
num1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(num1[0,0])
print(num1.ndim)

10
2


In [9]:
print(num1[:])

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [10]:
print([num1[::-1]])

[array([[70, 80, 90],
       [40, 50, 60],
       [10, 20, 30]])]


In [14]:
n =np.array([0,1,2,3,4,5,6,7,8,11])

In [15]:
print(n[::-1])

[11  8  7  6  5  4  3  2  1  0]


In [16]:
n=np.array([[10,20,30,],
            [40,50,60]])
print(n[0:2,0:2])

[[10 20]
 [40 50]]


In [1]:
import numpy as np

# Create a 3x4 array
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(arr_2d[1:3,2:4])

[[ 7  8]
 [11 12]]


In [19]:
arr_2d.shape

(3, 4)

In [2]:
for index, value in np.ndenumerate(arr_2d):
    print(index,value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12
