In [5]:
import tensorflow as tf

In [6]:
import platform
print(platform.architecture())


('64bit', 'WindowsPE')


In [4]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.10.0


In [7]:
tf.constant(4.0)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [8]:
tf.constant(4)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [9]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
y =tf.ones((3,3))

In [11]:
print(y)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [12]:
z = tf.ones((3,4))

In [13]:
print(z)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [16]:
z =tf.zeros((4,4))

In [17]:
print(z)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)


In [18]:
print(tf.eye(3))
#it prints out all the diagonal 1 of 3 by 3 matrics

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [22]:
#
x= tf.random.normal((1,3),mean=0,stddev=1)

In [23]:
print(x)

tf.Tensor([[ 1.4990265  -0.84585726 -0.96494573]], shape=(1, 3), dtype=float32)


In [24]:
x = tf.random.uniform((1,3), minval=0,maxval=1)

In [25]:
print(x)

tf.Tensor([[0.5601076 0.8945532 0.6145594]], shape=(1, 3), dtype=float32)


In [27]:
#to list values from start to limit with delta differnce
x = tf.range(start=1, limit=10,delta =2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [29]:
#to change the data type in to float
print(tf.cast(x, dtype=tf.float64))

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [31]:
#to add two vectors
x= tf.constant([1,2,3])
y =tf.constant([9,8,7])
z=tf.add(x,y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [32]:
#to add two vectors or tensors
z= x+y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [33]:
#to subtract the two tensors
z=x-y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [ ]:
#we can use all the four maths  operations by using tf.operation name

In [42]:
 #Indexing
x= tf.constant([1,2,3,4,5,6,7,8,9])

In [35]:
#it prints values from the first excluding the last that we set limit
print(x[0:5])

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [36]:
print(x[-1])

tf.Tensor(9, shape=(), dtype=int32)


In [38]:
print(x[::2])

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [40]:
#to print all values in reverse
# lets use this x[::-1] 
print(x[::-1])

tf.Tensor([9 8 7 6 5 4 3 2 1 0], shape=(10,), dtype=int32)


In [43]:
# reshaping means changing the shape of a tensor without altering its data
x =tf.reshape(x,(3,3))

In [44]:
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [54]:
x=tf.transpose(x,perm=[1,0])
print(x)

tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int32)
